# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'OTP',
            },
        ),
    ]
