# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-01 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyUser', '0019_hcworker_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manangers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(blank=True, to='MyUser.HCWorker')),
            ],
        ),
    ]
