# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-01 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='manangers',
            new_name='managers',
        ),
    ]
