# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_usergroup_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
