# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyUser', '0004_auto_20200326_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Facility Type',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.FacilityType'),
        ),
        migrations.AddField(
            model_name='facility',
            name='hcmanager',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='hcworker',
            field=models.ManyToManyField(to='MyUser.HCWorker'),
        ),
    ]
