# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-30 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicIllness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Chronic Illness',
            },
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterField(
            model_name='facility',
            name='hcmanager',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facility',
            name='hcworker',
            field=models.ManyToManyField(blank=True, to='MyUser.HCWorker'),
        ),
    ]
