# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-31 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20200330_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='hcworker',
        ),
    ]
