# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-01 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_remove_facility_hcworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunodeficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiency_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Immunodeficiency',
            },
        ),
    ]
