# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-13 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_immunodeficiency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Organization'},
        ),
    ]
