# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-13 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0021_auto_20200401_1734'),
        ('facility', '0005_auto_20200413_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='hcw_types',
            field=models.ManyToManyField(null=True, to='MyUser.HCWType'),
        ),
    ]
