# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-24 19:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0007_auto_20200425_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facility.CommunicationLanguage', verbose_name='Communication Language'),
            preserve_default=False,
        ),
    ]
