# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-25 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0008_facility_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='hcmanager',
        ),
    ]
