# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Facility',
            },
        ),
        migrations.AlterModelOptions(
            name='hcworker',
            options={'verbose_name': 'Health Care Worker'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Health Care Manager'},
        ),
        migrations.AddField(
            model_name='facility',
            name='hcmanager',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='hcworker',
            field=models.ManyToManyField(to='MyUser.HCWorker'),
        ),
    ]
