# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0003_auto_20200326_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='hcmanager',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='hcworker',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
