# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0004_auto_20200326_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCWType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcw_type_name', models.CharField(max_length=50, verbose_name='Health care worker type name')),
            ],
            options={
                'verbose_name': 'Health care worker type',
            },
        ),
        migrations.CreateModel(
            name='ResultStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_status', models.CharField(max_length=50, verbose_name='Result status')),
            ],
            options={
                'verbose_name': 'Result status',
                'verbose_name_plural': 'Result statuses',
            },
        ),
    ]
