# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0008_auto_20200326_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcworker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hcworker',
            name='employee_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hcworker',
            name='hcw_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyUser.HCWType', verbose_name='Job Title'),
        ),
    ]
