# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0011_auto_20200327_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcworker',
            name='hcw_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyUser.HCWType', verbose_name='Job Title'),
            preserve_default=False,
        ),
    ]
