# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0012_auto_20200327_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcworker',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
