# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0013_auto_20200328_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcworker',
            name='date_positive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
