# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-30 09:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20200330_1430'),
        ('MyUser', '0014_hcworker_date_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcworker',
            name='chronic_illnesses',
            field=models.ManyToManyField(blank=True, to='facility.ChronicIllness'),
        ),
        migrations.AddField(
            model_name='hcworker',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 3, 30, 14, 32, 31, 71772)),
            preserve_default=False,
        ),
    ]
