# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-31 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0017_auto_20200330_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcworker',
            name='immunodeficiency',
            field=models.BooleanField(default=False),
        ),
    ]
