# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-01 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0019_hcworker_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcworker',
            name='manager',
        ),
    ]
