# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-01 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_immunodeficiency'),
        ('MyUser', '0020_remove_hcworker_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcworker',
            name='immunodeficiency',
        ),
        migrations.AddField(
            model_name='hcworker',
            name='immunodeficiencies',
            field=models.ManyToManyField(blank=True, to='facility.Immunodeficiency'),
        ),
    ]
