# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0021_auto_20200401_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcworker',
            name='is_consented',
            field=models.BooleanField(default=False),
        ),
    ]
