# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-25 11:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0009_remove_facility_hcmanager'),
        ('MyUser', '0024_myuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcworker',
            name='facility',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='facility.Facility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='facility',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='facility.Facility'),
            preserve_default=False,
        ),
    ]
