# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-25 11:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0009_remove_facility_hcmanager'),
        ('MyUser', '0025_auto_20200425_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='facility',
        ),
        migrations.AddField(
            model_name='myuser',
            name='organization',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='facility.Facility', verbose_name='Organization'),
            preserve_default=False,
        ),
    ]
