# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-26 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0026_auto_20200425_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcworker',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hcworker',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
