# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('MyUser', '0007_hcworker_result_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
            options={
                'verbose_name': 'Survey Answer',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_url', models.CharField(max_length=500)),
                ('survey_date', models.DateTimeField()),
                ('sent_time', models.DateTimeField()),
                ('submitted_time', models.DateTimeField()),
                ('health_worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyUser.HCWorker')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyUser.ResultStatus')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
            options={
                'verbose_name': 'Survey Instance',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
            options={
                'verbose_name': 'Survey Question',
            },
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='survey_instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyInstance'),
        ),
    ]
