# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinstance',
            name='result_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyUser.ResultStatus'),
        ),
    ]
