# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-01 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200328_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
