"""
Django settings for hcwtracker project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

#   Licensed to the Apache Software Foundation (ASF) under one
#   or more contributor license agreements.  See the NOTICE file
#   distributed with this work for additional information
#   regarding copyright ownership.  The ASF licenses this file
#   to you under the Apache License, Version 2.0 (the
#   "License"); you may not use this file except in compliance
#   with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing,
#   software distributed under the License is distributed on an
#   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#   KIND, either express or implied.  See the License for the
#   specific language governing permissions and limitations
#   under the License.
#
#   Built and managed with Open Source Love by BeeHyv Software Solutions Pvt Ltd. Hyderabad
#   www.beehyv.com

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4!unrlx$t$3x8sfy&x=r)x=6*hz(7_rjj@@#9=&)qyibawcant'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '*']

# Application definition

INSTALLED_APPS = [
    'MyUser',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'hcwtracker',
    'facility',
    'survey',
    'question',
    'groups',
    'otpvalidation'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'hcwtracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'hcwtracker.wsgi.application'
LOGIN_URL = '/accounts/login/'
AUTH_USER_MODEL = 'MyUser.MyUser'
# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
LOGIN_REDIRECT_URL = '/admin'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True
# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

FRONTEND_URL = ''

INFOBIP_URL = ''
INFOBIP_TOKEN = ''


MESSAGES = {
    "english": {
        1: {
            "header": "Workforce Healthcare: Survey submitted",
            "message": "Hi {first_name},\n\nThank you for the submitting the survey. Based on your responses, we advice you to do the following:\n\n{health_status}"
        },
        2: {
            "header": "Workforce Healthcare: New Survey",
            "message": "Hi {first_name},\n\nA new survey has been generated for you. Please fill the new survey by visiting the link provided below:\n{survey_link}"
        },
        3: {
            "header": "Workforce Healthcare: Your status has been updated",
            "message": "Hi {first_name},\n\nYour manager has updated your health status to {new_status}"
        },
        4: {
            "header": "Workforce Healthcare: Survey Submitted",
            "message": "Hi {first_name},\n\nThank you for submitting the survey. "
        },
        5:{
            "header": "Workforce Healthcare: OTP",
            "message": "Hi {first_name},\n\nA new OTP has been generated for you. OTP - {otp}"
        }
    },
    "hindi": {
        1: {
            "header": "Workforce Healthcare: Survey submitted",
            "message": "प्रिय {first_name},\n\n सर्वेक्षण प्रस्तुत करने के लिए धन्यवाद। आपकी प्रतिक्रियाओं के आधार पर, हम आपको निम्नलिखित करने की सलाह देते हैं\n{health_status}"
        },
        2: {
            "header": "Workforce Healthcare: New Survey",
            "message": "प्रिय {first_name},\n\nआपके लिए एक नया सर्वेक्षण तैयार किया गया है। कृपया नीचे दिए गए लिंक पर जाकर नया सर्वेक्षण भरें:\n{survey_link}"
        },
        3: {
            "header": "Workforce Healthcare: Your status has been updated",
            "message": "प्रिय {first_name},\n\nआपके प्रबंधक ने आपकी स्वास्थ्य स्थिति को  अपडेट कर दिया है:\n{new_status}"
        },
        4: {
            "header": "Workforce Healthcare: Survey Submitted",
            "message": "प्रिय {first_name},\n\n सर्वेक्षण जमा करने के लिए धन्यवाद।"
        },
        5:{
            "header":"Workforce Healthcare: OTP",
            "message": "प्रिय {first_name},\n\n आपका नया - {otp}।"
        }
    }

}
