# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Question',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Question Type',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.QuestionType'),
        ),
    ]
